import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir} from 'node:fs/promises';
import {startReview} from './review-harness.mjs';
const {browser,server}=await startReview(3012);
const page=await browser.newPage({viewport:{width:390,height:900}}),errors=[];page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:3012',sel=n=>page.locator('[name="'+n+'"]');
const shotDir='test-results/branches';await mkdir(shotDir,{recursive:true});
async function next(p=page){await p.locator('#ff-next').click();await p.waitForFunction(()=>!document.getElementById('ff-next').disabled);if(await p.locator('#ff-errors').isVisible())throw new Error((await p.locator('#step-title').innerText())+': '+await p.locator('#ff-errors').innerText());}
async function until(title,p=page){for(let i=0;i<35;i++){if(await p.locator('#step-title').innerText()===title)return;await next(p);}throw Error('Missing block '+title);}
async function values(map){for(const[n,v]of Object.entries(map)){const e=sel(n);if(await e.evaluate(x=>x.tagName)==='SELECT')await e.selectOption(v);else await e.fill(v);}}
try{
 await page.goto(base+'/fact-find.html');await page.locator('#ff-example').click();assert.equal(await sel('applicant.sharedEmail').isChecked(),true);await sel('applicant.sharedEmail').uncheck();await page.locator('#ff-next').click();assert.equal(await sel('applicant.personalEmail').getAttribute('aria-invalid'),'true');await sel('applicant.personalEmail').fill('personal@example.invalid');await next();
 assert.equal(await sel('business.number').getAttribute('required'),'');assert.equal(await sel('business.number').locator('..').locator('.optional').count(),0);await sel('business.number').fill('');await page.locator('#ff-next').click();assert.equal(await sel('business.number').getAttribute('aria-invalid'),'true');await sel('business.number').fill('12345678');await next();
 await sel('business.differentName').selectOption('yes');await sel('business.tradingName').fill('Example Shop');await sel('business.sameAddress').selectOption('yes');assert.equal(await sel('business.trading.address').isVisible(),false);await next();await until('Business bank accounts');await sel('financial.bank').selectOption('other');await sel('financial.bankOther').fill('');await page.locator('#ff-next').click();assert.equal(await sel('financial.bankOther').getAttribute('aria-invalid'),'true');await sel('financial.bankOther').fill('Example Bank');await page.locator('#add-bank').click();await sel('banks.1.provider').selectOption('Monzo');await sel('financial.overdraft').selectOption('yes');await sel('financial.overdraftAmount').fill('5000');await next();
 assert.equal(await page.locator('[data-provider-search]').count(),0);await sel('financial.processorCount').fill('2');await sel('financial.processorCount').dispatchEvent('change');await sel('processors.1.provider').selectOption('other');await sel('processors.1.providerOther').fill('Second Processor');await sel('financial.locations').fill('2');await sel('financial.locations').dispatchEvent('change');await page.locator('#ff-next').click();assert.equal(await sel('locations.1.address').getAttribute('aria-invalid'),'true');await values({'locations.1.postcode':'AB1 2CD','locations.1.address':'2 Example Shop Street'});await page.screenshot({path:shotDir+'/card-locations-mobile.png',fullPage:true});await next();await until('Person 1: about them');
 await page.locator('[data-use-applicant="0"]').click();await sel('owners.0.nationality').selectOption('Indian');await sel('owners.0.immigrationStatus').selectOption('Visa holder / limited leave');await page.locator('#ff-next').click();assert.equal(await sel('owners.0.visaRoute').getAttribute('aria-invalid'),'true');await sel('owners.0.visaRoute').selectOption('Skilled Worker');await next();assert.equal(await sel('owners.0.email').inputValue(),'personal@example.invalid');await until('Existing business loans');
 await sel('questions.loans').selectOption('yes');await page.locator('#ff-next').click();assert.equal(await page.locator('#step-title').innerText(),'Existing business loans');assert.equal(await page.locator('.loan-types.has-error').count(),1);assert.match(await page.locator('#ff-errors').innerText(),/Select at least one/);await sel('loanTypes.ggs').check();await values({'loans.0.original':'50000','loans.0.outstanding':'25000','loans.0.lender':'Example Lender'});await page.locator('[data-add-loan-type="ggs"]').click();await values({'loans.1.original':'10000','loans.1.outstanding':'5000','loans.1.lender':'Second Lender'});assert.equal(await sel('loans.0.taken').getAttribute('required'),null);await next();await until('Your business, in a little more detail');assert.equal(await sel('business.premises').isVisible(),false);await sel('business.addPremises').check();await sel('business.premises').selectOption('Rented');assert.equal(await sel('business.landlord').count(),1);assert.equal(await sel('business.landlord').isVisible(),false);await sel('business.morePremises').check();await sel('business.landlord').fill('Example Landlord');await sel('business.franchise').check();await values({'business.franchiseName':'Example Brand','business.franchiseType':'Food / hospitality'});await next();
 assert.equal(await sel('application.acceptance').isDisabled(),false);assert.equal(await page.locator('.inline-terms').isVisible(),true);assert.equal(await page.locator('.ff-review-ack a[href="/privacy_policy.html"]').count(),1);await page.locator('#ff-next').click();assert.equal(await page.locator('.ff-review-ack .has-error').count(),3);await page.locator('.ff-terms').scrollIntoViewIfNeeded();await page.screenshot({path:shotDir+'/terms-mobile.png'});
 assert.match(await page.locator('#fields').textContent(),/Second Processor/);assert.match(await page.locator('#fields').textContent(),/Example Shop/);assert.match(await page.locator('#fields').textContent(),/Monzo/);
 console.log('PASS: business branches, personal email, mandatory CRN, independent trading name, bank/processor/location repeats, visa details, immediate loan errors, optional premises/franchise, inline acceptance.');
 // Dedicated property enquiry, reusing identity fixture while skipping unrelated business fields.
 await page.goto(base+'/fact-find.html');await page.locator('#ff-example').click();await sel('funding.route').selectOption('property');await until('Your property plans');assert.equal(await sel('financial.turnover').count(),0);await values({'property.purpose':'remortgage','property.owner':'My business','property.type':'mixed','property.occupied':'no','property.flats':'2','property.shops':'1'});await next();await values({'property.location.postcode':'AB1 2CD','property.location.address':'10 Example Mixed Use Street','property.purchasePrice':'200000','property.purchaseDate':'2020-01-01','property.value':'300000','property.debt':'100000','property.lender':'Existing Lender'});assert.match(await page.locator('#property-equity').innerText(),/£100,000/);assert.match(await page.locator('#property-equity').innerText(),/£200,000/);await next();
 await values({'property.repayment':'interest','property.term':'5','property.termUnit':'Years','property.minimumTerm':'3','property.maximumTerm':'7','property.exit':'Refinance / new mortgage','property.timescale':'One to three months'});await next();await sel('property.rented').selectOption('rented');await values({'property.rent':'2500','property.tenancy':'Mixed commercial and residential','property.occupiedFlats':'3'});await page.locator('#ff-next').click();assert.equal(await sel('property.occupiedFlats').getAttribute('aria-invalid'),'true');await sel('property.occupiedFlats').fill('2');await next();await sel('owners.0.nationality').selectOption('Irish');assert.equal(await sel('owners.0.immigrationStatus').count(),0);await until('Check and accept');assert.equal(await sel('application.noPropertyPurchase').count(),0);assert.doesNotMatch(await page.locator('#fields').textContent(),/Average monthly card sales|Revenue from online sales|Annual turnover/);for(const name of ['businessUse','acceptance'])await sel('application.'+name).check();await next();assert.match(await page.locator('#ff-end').innerText(),/nothing has been sent or saved/);assert.match(await page.locator('#ff-end').innerText(),/alex@example.invalid/);assert.doesNotMatch(await page.locator('#ff-end').innerText(),/SignWell/);console.log('PASS: property remortgage, mixed-use income, two equity comparisons, five-year interest-only exit, Irish status, conditional declarations and truthful preview completion.');
 // Agent assistance still cannot provide client acceptance.
 await page.goto(base+'/fact-find.html');await page.locator('#ff-example').click();await page.locator('.conversation-tools summary').click();await sel('journey.mode').selectOption('phone');await until('Check and accept');assert.equal(await sel('application.acceptance').count(),0);assert.equal(await sel('application.businessUse').count(),0);
 // Protected adapter mocked locally: no real API, email or CRM record.
 const live=await browser.newPage();live.setDefaultTimeout(8000);live.on('pageerror',e=>errors.push(e.message));let revision=0,submitted=0,verified=false,failSave=false,failCallback=false;const calls=[];let lastSnapshot;
 await live.route('**/runtime-config.js',route=>route.fulfill({contentType:'text/javascript',body:"export const runtime={mode:'live',apiBase:'/api/intake/v1',turnstileSiteKey:'test-site-key'};"}));
 await live.route('https://challenges.cloudflare.com/**',route=>route.fulfill({contentType:'text/javascript',body:"window.turnstile={render:(c,o)=>{queueMicrotask(()=>o.callback('test-token'));return 1;},remove:()=>{}};"}));
 await live.route('**/api/intake/v1/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname.split('/v1')[1],body=req.method()==='POST'?req.postDataJSON():{};calls.push({path,body,key:req.headers()['idempotency-key']});let data={};if(path==='/session')data={contract:'pay2day-intake-v1',acceptingEnquiries:true,csrfToken:'test-csrf'};else{assert.equal(req.headers()['x-csrf-token'],'test-csrf');assert.ok(req.headers()['idempotency-key']);if(path==='/enquiries')data={applicationId:'test-application',revision:++revision};else if(path==='/draft/save'){assert.equal(body.revision,revision);if(failSave){failSave=false;return route.fulfill({status:503,json:{}});}lastSnapshot=body.fields;assert.ok(body.block);data={revision:++revision};}else if(path==='/callback/request'){assert.equal(body.applicationId,'test-application');assert.equal(body.revision,revision);if(failCallback){failCallback=false;return route.fulfill({status:503,json:{}});}lastSnapshot=body.fields;data={applicationId:'test-application',revision:++revision,callbackSaved:true,confirmationStatus:'queued'};}else if(path==='/verification/request'){assert.equal(body.revision,revision);data={sent:true};}else if(path==='/verification/confirm'){verified=true;data={verified:true};}else if(path==='/submission'){assert.equal(body.revision,revision);assert.equal(body.accepted,true);assert.equal(body.businessUse,true);assert.equal(body.noPropertyPurchase,true);assert.ok(verified);submitted++;data={reference:'P2D-TEST'};}else if(path==='/lookups/companies')data={items:[]};else throw Error('Unexpected endpoint '+path);}await route.fulfill({json:data});});
 await live.goto(base+'/fact-find.html');await live.locator('#ff-example').evaluate(el=>el.click());await next(live);assert.equal(calls.filter(c=>c.path==='/enquiries').length,1);assert.equal(calls.filter(c=>c.path==='/draft/save').length,1);
 failSave=true;await live.locator('#ff-next').click();await live.waitForFunction(()=>!document.getElementById('ff-next').disabled);assert.equal(await live.locator('#step-title').innerText(),'Business details');assert.equal(await live.locator('#ff-errors').isVisible(),true);await next(live);
 await live.locator('[name="business.registered.address"]').fill('Partly entered address');failCallback=true;await live.locator('.form-callback button').click();await live.locator('#lead-submit').click();await live.waitForFunction(()=>!document.getElementById('lead-submit').disabled);assert.match(await live.locator('#lead-status').innerText(),/could not complete/);await live.locator('#lead-submit').click();await live.waitForFunction(()=>document.getElementById('lead-status').textContent.includes('request is saved'));assert.equal(lastSnapshot['business.registered.address'],'Partly entered address');assert.equal(calls.filter(c=>c.path==='/enquiries').length,1);const cb=calls.filter(c=>c.path==='/callback/request');assert.equal(cb.length,2);assert.equal(cb[0].key,cb[1].key);assert.deepEqual(cb[0].body,cb[1].body);await live.locator('#lead-dialog .close-button').click();
 await until('Check and accept',live);for(const n of ['businessUse','noPropertyPurchase','acceptance'])await live.locator('[name="application.'+n+'"]').check();await live.locator('#ff-next').click();await live.locator('#verification-code').fill('123456');await live.locator('#verify-email').click();await live.waitForFunction(()=>document.getElementById('verification-status').textContent.includes('confirmed'));await live.locator('#ff-next').click();await live.waitForFunction(()=>!document.getElementById('ff-end').hidden);assert.match(await live.locator('#ff-end').innerText(),/Thank you/);assert.equal(submitted,1);assert.equal(calls.filter(c=>c.path==='/enquiries').length,1);await live.close();console.log('PASS: one draft, every-block snapshot, failed-save retention, partial callback on same record, retry idempotency, client verification and final declarations (mock API).');
 // Calculator UI and page geometry.
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:950});for(const path of ['/property-finance-calculator.html','/fact-find.html','/','/fixed-direct-debit-loans.html']){await page.goto(base+path);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,path+' overflow '+width);if(path==='/property-finance-calculator.html'){await page.locator('[name="product"]').selectOption('interest');await page.locator('[name="rate"]').fill('6');await page.locator('#property-calculator button[type=submit]').click();assert.match(await page.locator('#property-output').innerText(),/£1,250.00/);if([1440,390].includes(width))await page.screenshot({path:shotDir+'/property-calculator-'+width+'.png',fullPage:true});}}}
 assert.deepEqual(errors,[]);console.log('PASS: property calculator UI and responsive geometry at 1440 / 768 / 390 / 320 px; no browser runtime errors.');
}finally{await browser.close();server.kill();}
