import test from 'node:test';
import assert from 'node:assert/strict';
import {validate,assess,contextNotes,parseMoney,unsecuredScreen,illustrateLoan} from '../public/logic.js';
const base={amount:'25,000',purpose:'stock',repayment:'sales',uk:'yes',entity:'limited',trading:'2plus',turnover:'30,000',pattern:'steady',cards:'yes',cardAmount:'20,000',terminal:'yes',propertyOwner:'yes'};
test('valid figures and sales-linked preferences have explicit underwriting caveat',()=>{const {data,errors}=validate(base);assert.equal(errors.length,0);const r=assess(data);assert.deepEqual(r.slice(0,2).map(x=>x.id),['mca','terminal']);assert.equal(r[0].status,'May be eligible');assert.match(r[0].reason,/Subject to lender underwriting and approval/);});
test('monthly, frequent and drawdown preferences align their supported routes',()=>{for(const [repayment,id] of [['monthly','term'],['monthly','dd'],['frequent','dd'],['flexible','loc']])assert.equal(assess(validate({...base,repayment}).data).find(r=>r.id===id).status,'May be eligible');});
test('no card sales cannot produce aligned card funding',()=>{const r=assess(validate({...base,cards:'no',cardAmount:'999999'}).data);for(const id of ['terminal'])assert.equal(r.find(x=>x.id===id).status,'Requires card sales');});
test('rejects empty, nonnumeric, malformed and negative money',()=>{for(const amount of ['', 'banana','-2','1,2','Infinity','1e6','1.234','0','1000000001'])assert.ok(validate({...base,amount}).errors.some(e=>e.field==='amount'));assert.equal(parseMoney('25,000.50'),25000.5);});
test('card turnover cannot exceed total and zero turnover needs pre-trading',()=>{assert.ok(validate({...base,cardAmount:'40,000'}).errors.some(e=>e.field==='cardAmount'));assert.ok(validate({...base,turnover:'0'}).errors.some(e=>e.field==='turnover'));});
test('pre-trading has no aligned routes or revenue assumptions',()=>{const v=validate({...base,trading:'pre',turnover:'0',cards:'no'});assert.equal(v.errors.length,0);assert.ok(assess(v.data).every(r=>r.status==='Trading review needed'));assert.match(contextNotes(v.data)[0].title,/No trading history/);});
test('pre-trading with revenues is inconsistent',()=>{assert.ok(validate({...base,trading:'pre'}).errors.some(e=>e.field==='trading'));});
test('UK and business-purpose scope stop personalised alignment',()=>{for(const patch of [{uk:'no'},{purpose:'personal'}]){const d=validate({...base,...patch}).data;assert.ok(assess(d).every(r=>r.status==='Overview only'));assert.match(contextNotes(d)[0].title,/Outside/);}});
test('sole traders, partnerships and unknown structures need scope review',()=>{for(const entity of ['sole','partnership','other'])assert.ok(assess(validate({...base,entity}).data).every(r=>r.status==='Scope check needed'));});
test('terminal setup and seasonal fixed payment cautions appear',()=>{const r=assess(validate({...base,terminal:'no',pattern:'variable'}).data);assert.equal(r.find(r=>r.id==='terminal').status,'Setup review needed');assert.match(r.find(r=>r.id==='term').reason,/sales vary/);});
test('amount changes are reflected in data, never a fabricated provider limit',()=>{assert.equal(validate({...base,amount:'1000000'}).data.amount,1000000);assert.ok(assess(validate({...base,amount:'1000000'}).data).every(r=>!r.reason.includes('approved')));});

test('two repayment preferences align both types without duplicates',()=>{const d=validate({...base,repayment:'monthly',repayment2:'sales'});assert.equal(d.errors.length,0);assert.equal(assess(d.data).filter(r=>r.status==='May be eligible').length,4);assert.ok(validate({...base,repayment2:'sales'}).errors.some(e=>e.field==='repayment2'));});
test('property screening boundary at £50,000 and guarantee review',()=>{assert.equal(unsecuredScreen({...base,amount:50000,propertyOwner:'no'}).tone,'neutral');assert.equal(unsecuredScreen({...base,amount:50000.01,propertyOwner:'no'}).tone,'caution');assert.equal(unsecuredScreen({...base,amount:100000,propertyOwner:'yes'}).tone,'neutral');assert.equal(unsecuredScreen({...base,amount:100000,propertyOwner:'unsure'}).tone,'caution');assert.match(unsecuredScreen({...base,amount:25000}).text,/may be required/);});
test('illustrations validate assumptions, zero interest and amortisation',()=>{assert.deepEqual(illustrateLoan(12000,0,12),{monthly:1000,total:12000,interest:0});const v=illustrateLoan(10000,12,12);assert.ok(Math.abs(v.monthly-888.487886)<0.0001);assert.equal(illustrateLoan(10000,-1,12),null);assert.equal(illustrateLoan(10000,10,1.2),null);assert.equal(illustrateLoan(10000,NaN,12),null);});

test('open to all options and property branch do not fabricate lender eligibility',()=>{const v=validate({...base,repayment:'all'});assert.equal(v.errors.length,0);assert.equal(assess(v.data).length,5);assert.ok(assess(v.data).every(r=>r.status==='May be eligible'));const p=validate({...base,propertyFinance:'yes',propertyType:'mixed',propertyOccupied:'yes'});assert.equal(p.errors.length,0);assert.equal(assess(p.data).length,8);assert.ok(assess(p.data).filter(r=>r.property).every(r=>r.status==='Specialist scope check'));assert.ok(validate({...base,propertyFinance:'yes'}).errors.some(e=>e.field==='propertyType'));});
